FROM debian:stable-slim as buildarm
COPY . /tmp/e2guardian
WORKDIR /tmp/e2guardian
RUN apt-get update \
    && apt-get install --no-upgrade --no-install-recommends --no-install-suggests -y curl unzip automake \
    coreutils debianutils diffutils e2fsprogs findutils grep unzip ncurses-base \
    libevent-pthreads-* libevent-dev ncurses-bin login sysvinit-utils tar \
    libc6-dev libc-dev gcc g++ make dpkg-dev autotools-dev debhelper dh-autoreconf dpatch \
    libclamav-dev libpcre3-dev zlib1g-dev pkg-config libssl-dev libssl1.1 ca-certificates lsb-release inotify-tools curl \
    && ./autogen.sh && ./configure --host=arm-linux-gnueabihf --prefix=/usr --enable-clamd=yes --with-proxyuser=e2guardian --with-proxygroup=e2guardian --sysconfdir=/etc --localstatedir=/var --enable-icap=yes --enable-commandline=yes --enable-email=yes --enable-ntlm=yes --enable-pcre=yes --enable-sslmitm=yes \
    && make \
    && adduser --no-create-home --uid 1161 --group --system e2guardian \
    && cp src/e2guardian /usr/sbin/e2guardian \
    && cp -Rf configs /etc/e2guardian \
    && mkdir -p /usr/share/e2guardian/languages \
    && mkdir -p /run/e2guardian \
    && mkdir -p /var/log/e2guardian && chown -R e2guardian /var/log/e2guardian && chown -R e2guardian /etc/e2guardian && chown -R e2guardian /run/e2guardian \
    && cp -Rf data/languages /usr/share/e2guardian/ \
    && cp data/*.gif /usr/share/e2guardian/ \
    && cp data/*swf /usr/share/e2guardian/ \
    && rm -Rf /tmp/* \
    && sed -i "s/^#dockermode.*$/dockermode\ =\ on/" /etc/e2guardian/e2guardian.conf \
    && sed -i "s/^#pidfilename.*$/pidfilename\ =\ \/run\/e2guardian\/e2.pid/" /etc/e2guardian/e2guardian.conf \
    && export DEBIAN_FRONTEND="noninteractive" && apt-get remove -y --allow-remove-essential --purge libc-dev-bin libtommath-dev man-db libc6-dev libc-dev linux-libc-dev gcc unzip g++ make libevent-dev dpkg-dev autotools-dev debhelper dh-autoreconf dpatch libclamav-dev libpcre3-dev zlib1g-dev pkg-config libssl-dev cpp m4 automake \
    && chmod +x src/e2guardian && chown -Rf 1161 e2guardian/src \ 
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -Rf /var/lib/apt/lists/* 

FROM debian:stable-slim
COPY --from=buildarm /tmp/e2guardian/src/e2guardian /usr/sbin/e2guardian
COPY --from=buildarm /tmp/e2guardian/configs /etc/e2guardian
COPY --from=buildarm /tmp/e2guardian/data/languages /usr/share/e2guardian/
COPY --from=buildarm /tmp/e2guardian/data/*swf /usr/share/e2guardian/
RUN apt-get update && apt-get install --no-upgrade --no-install-recommends --no-install-suggests -y sed libevent-pthreads-* libssl1.1 ca-certificates curl \
    && adduser --no-create-home --uid 1161 --group --system e2guardian \
    && mkdir -p /usr/share/e2guardian/languages \
    && mkdir -p /run/e2guardian \
    && mkdir -p /var/log/e2guardian && chown -R e2guardian /var/log/e2guardian && chown -R e2guardian /etc/e2guardian && chown -R e2guardian /run/e2guardian \
    && rm -Rf /tmp/* \
    && sed -i "s/^#dockermode.*$/dockermode\ =\ on/" /etc/e2guardian/e2guardian.conf \
    && sed -i "s/^#pidfilename.*$/pidfilename\ =\ \/run\/e2guardian\/e2.pid/" /etc/e2guardian/e2guardian.conf \
    && sed -i "s/^#icapport.*$/icapport\ =\ 1344/" /etc/e2guardian/e2guardian.conf \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -Rf /var/lib/apt/lists/* 

HEALTHCHECK CMD curl http://localhost:8080/internal.test.e2guardian.org | grep "e2guardian" || exit 1
USER e2guardian
EXPOSE 8080
CMD ["e2guardian", "-N"]
 
HEALTHCHECK CMD curl http://localhost:8080/internal.test.e2guardian.org | grep "e2guardian" || exit 1
USER e2guardian
EXPOSE 8080
CMD ["e2guardian", "-N"]
